export PATH=$PATH:/prj/qca_sw_blr/user4/usasan/qsdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin
export PATH=$PATH:/prj/qca_sw_blr/user4/usasan/qsdk/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/bin
export PATH=$PATH:/prj/qca_sw_blr/user2/tools/p4v/bin/p4merge 
export PATH=$PATH:/prj/qca_sw_blr/user2/tools/scripts/repo
alias repo="/prj/qca_sw_blr/user2/tools/scripts/repo"
alias wifi="cd /usr2/usasan/ws/qsdk/qca/src/qca-wifi-10.4"
alias ws="cd /local/mnt/workspace" 
alias wifi_e="cd /local/mnt/workspace/ENDIVE/qsdk/qca/src/qca-wifi-10.4"
alias wifi_m="cd /local/mnt/workspace/MIPS/qsdk/qca/src/qca-wifi-10.4"
alias wifi_a="cd /local/mnt/workspace/ARUGULA/qsdk/qca/src/qca-wifi-10.4"
alias wifi_g="cd /local/mnt/workspace/GIT_1.0_ws/qsdk/qca/src/qca-wifi-10.4"
alias wifi_h="cd /local/mnt/workspace/HAWK/qsdk/qca/src/qca-wifi"
alias wifi_n="cd /local/mnt/workspace/ATF/qsdk/qca/src/qca-wifi-10.4"
alias hw_l="cd /local/mnt/workspace/HAWK_LATEST/qsdk/qca/src/qca-wifi"
alias mipst="cd /prj/qca_sw_blr/user4/usasan/qsdk/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin"
alias armt="cd /prj/qca_sw_blr/user4/usasan/qsdk/staging_dir/toolchain-arm_v7-a_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/bin"
alias mout="cd /usr2/usasan/ws/qsdk/build_dir/linux-ar71xx_generic/qca-wifi-10.4-gf632231-dirty-unified-perf/qca-wifi-10.4-gf632231-dirty/"
export CSCOPE_EDITOR=vim
